services:
  postgis:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    platform: linux/amd64
    container_name: postgis-container
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_postgis:/var/lib/postgresql/data
      - ./postgis-setup:/docker-entrypoint-initdb.d
    networks:
      data-station-network:
        ipv4_address: 172.20.14.89
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 5

  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.13.40
    container_name: clickhouse-container
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - db_clickhouse:/var/lib/clickhouse-storage
      - db_clickhouse_logs:/var/log/clickhouse-server
      - ./clickhouse-setup:/docker-entrypoint-initdb.d
    ports:
      - "9091:8123"
      - "9092:9000"
    networks:
      data-station-network:
        ipv4_address: 172.20.14.90
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    user: root
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE

volumes:
  db_postgis:
  db_clickhouse:
  db_clickhouse_logs:


networks:
  data-station-network:
    external: true
